### ISSUE TITLE
2.x default module fails if application.properties is not in the classpath

### ISSUE THREAD

**Issue by brharrington** [Netflix/archaius#304]
This test will fail if there is no `application.properties` file on the classpath:

``` java
@Test
public void getConfig() throws Exception {
  Guice.createInjector(new ArchaiusModule()).getInstance(Config.class);
}
```

The module specifies `.withFailOnFirst(false)`, but currently returns `null` if the properties file is missing resulting in:

```
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) null returned by binding at com.netflix.archaius.guice.ArchaiusModule.getApplicationLayer()
 but parameter 4 of com.netflix.archaius.guice.ArchaiusModule.getConfig() is not @Nullable
  at com.netflix.archaius.guice.ArchaiusModule.getApplicationLayer(ArchaiusModule.java:185)
  while locating com.netflix.archaius.Config annotated with @com.netflix.archaius.inject.ApplicationLayer()
    for parameter 4 at com.netflix.archaius.guice.ArchaiusModule.getConfig(ArchaiusModule.java:284)
  at com.netflix.archaius.guice.ArchaiusModule.getConfig(ArchaiusModule.java:284)
  at com.netflix.archaius.guice.ArchaiusModule.getConfig(ArchaiusModule.java:284)
  while locating com.netflix.archaius.Config
    for field at com.netflix.archaius.guice.ConfigurationInjectingListener.rootConfig(ConfigurationInjectingListener.java:27)
  at com.netflix.archaius.guice.ArchaiusModule.configure(ArchaiusModule.java:122)

2) null returned by binding at com.netflix.archaius.guice.ArchaiusModule.getApplicationLayer()
 but parameter 4 of com.netflix.archaius.guice.ArchaiusModule.getConfig() is not @Nullable
  at com.netflix.archaius.guice.ArchaiusModule.getApplicationLayer(ArchaiusModule.java:185)
  while locating com.netflix.archaius.Config annotated with @com.netflix.archaius.inject.ApplicationLayer()
    for parameter 4 at com.netflix.archaius.guice.ArchaiusModule.getConfig(ArchaiusModule.java:284)
  at com.netflix.archaius.guice.ArchaiusModule.getConfig(ArchaiusModule.java:284)
  at com.netflix.archaius.guice.ArchaiusModule.getConfig(ArchaiusModule.java:284)
  while locating com.netflix.archaius.Config
    for parameter 0 at com.netflix.archaius.guice.ArchaiusModule.getLoader(ArchaiusModule.java:214)
  at com.netflix.archaius.guice.ArchaiusModule.getLoader(ArchaiusModule.java:214)
  at com.netflix.archaius.guice.ArchaiusModule.getLoader(ArchaiusModule.java:214)
  while locating com.netflix.archaius.ConfigLoader
    for field at com.netflix.archaius.guice.ConfigurationInjectingListener.loader(ConfigurationInjectingListener.java:27)
  at com.netflix.archaius.guice.ArchaiusModule.configure(ArchaiusModule.java:122)

2 errors
    at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:466)
    at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:176)
    at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
    at com.google.inject.Guice.createInjector(Guice.java:96)
    at com.google.inject.Guice.createInjector(Guice.java:73)
    at com.google.inject.Guice.createInjector(Guice.java:62)
    at com.netflix.iep.archaius1.ArchaiusModuleTest.getConfig(ArchaiusModuleTest.java:70)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
```

**Comment by rgallardo-netflix** [comment]
Not sure when this got fixed, but the test passes in 2.5.0
