### ISSUE TITLE
archaius-scala does not work for Scala 2.12

### ISSUE THREAD

**Issue by mmlac** [Netflix/archaius#497]
```
java.lang.NoClassDefFoundError: scala/Product$class
	at com.netflix.config.scala.CallbackWrapper.<init>(DynamicProperty.scala:84)
	at com.netflix.config.scala.PropertyBox.addCallback(DynamicProperty.scala:97)
	at com.netflix.config.scala.DynamicProperty$class.addCallback(DynamicProperty.scala:68)
	at com.netflix.config.scala.DynamicStringProperty.addCallback(DynamicStringProperty.scala:36)
	at .........
Caused by: java.lang.ClassNotFoundException: scala.Product$class
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 31 more
```

Scala 2.12 has changed their naming and because archaius-scala is built with 2.10 it cannot find the classes any more.

Created PR #496

**Comment by rgallardo-netflix** [comment]
V1 is no longer maintained
